Uno R4 OTA
arduino/ArduinoCore-renesas pull request #100
Opened 2023-08-21 12:23 UTC by pennam

Apply after #99 
Needs WiFi firmware 0.3.0 -> https://github.com/arduino/uno-r4-wifi-usb-bridge/releases/tag/0.3.0-rc1

2023-08-21 12:39 UTC, JAndrassy commented
Uno R4 **WiFi** OTA

2023-08-21 16:15 UTC, per1234 requested changes

2023-08-21 16:15 UTC, per1234 commented on libraries/OTAUpdate/examples/WiFiFirmwareOTA/WiFiFirmwareOTA.ino
> +  This sketch demonstrates how to make an self OTA Update the UNO R4 WiFi Firmware
```suggestion
  This sketch demonstrates how to make the UNO R4 WiFi self-update its Wi-Fi module firmware via OTA
```

The previous wording was incorrect.

My intent was for my suggested text to have the same meaning as what was intended by the former text, but the meaning of the former text was difficult to decipher so it is possible I inadvertently shifted the meaning.

2023-08-21 16:15 UTC, per1234 commented on libraries/OTAUpdate/examples/WiFiFirmwareOTA/WiFiFirmwareOTA.ino
> +  Serial.print("Current WIFi firmware version: ");
```suggestion
  Serial.print("Current WiFi firmware version: ");
```
Fix case of letter.

The correct spelling is actually the hyphenated "[Wi-Fi](https://en.wikipedia.org/wiki/Wi-Fi)". This spelling is not used in Arduino product names due to being trademarked, but in my opinion the correct spelling should be used in prose such as this comment where there should be no problem with trademark infringement. But I'll settle for just changing the letter case.

2023-08-22 14:53 UTC, pennam commented
[ci](https://github.com/arduino/ArduinoCore-renesas/actions/runs/5940093056/job/16107924184?pr=100) is failing because library is not included in the previous core releases.

2023-08-30 12:13 UTC, merged