fixing millis rollover bug x2
arduino/ArduinoCore-renesas pull request #196
Opened 2023-11-27 03:49 UTC by delta-G

Fix TwoWire::read_from and TwoWire::write_to to use proper millis code that can handle rollover.  
Fixes issue https://github.com/arduino/ArduinoCore-renesas/issues/195

2023-11-28 08:05 UTC, aentinger commented on libraries/Wire/Wire.cpp
> +    uint32_t startMillis = millis();
```suggestion
    uint32_t const start = millis();
```
Use const correctness ;)

2023-11-28 08:06 UTC, aentinger requested changes
LGTM :+1: However, please use either "underscore case" `start_millis` or drop the `millis` suffix, since all other variables here seem to be non CamelCase.

2023-11-28 23:10 UTC, delta-G commented
I just changed the name to start as suggested.  It looks like everything compiles now.  Please let me know if it needs anything else.  

Thanks!

2023-11-29 05:35 UTC, aentinger approved these changes
LGTM :+1:

2023-11-29 05:36 UTC, merged