ESPHost - fix softAP password check
arduino/ArduinoCore-renesas pull request #248
Opened 2024-01-23 18:56 UTC by JAndrassy

SoftAP password length was checked for open network and was not checked for secured

2024-02-15 10:55 UTC, pennam requested changes
@JAndrassy i think it should be like this

```
if ((cfg.encryption_mode != WIFI_AUTH_OPEN) && 
     ((strlen((char *)&cfg.pwd) > MAX_PWD_LENGTH) ||
      (strlen((char *)&cfg.pwd) < MIN_PWD_LENGTH))) {
```

2024-02-15 12:17 UTC, JAndrassy commented
yes. I just did a quick fix because I got error about password for WIFI_AUTH_OPEN and at the same time I released that just before that I used a short password and it took me a while to figure out why the PC doesn't want to connect.
I can't modify and retest the PR right now.

2024-02-15 18:47 UTC, JAndrassy commented
done

2024-02-16 10:43 UTC, pennam approved these changes
Thanks @JAndrassy

2024-02-16 10:43 UTC, merged