Core renesas / Storage library, Fix for #366 (Name conflict in library Storage)
arduino/ArduinoCore-renesas pull request #370
Opened 2024-08-28 15:11 UTC by maidnl

Renamed storage debug function to avoid clash with user code

2024-08-29 07:23 UTC, facchinm approved these changes

2024-08-29 07:23 UTC, facchinm requested changes

2024-08-29 07:23 UTC, facchinm commented on libraries/Storage/storage_common.h
> +static inline void _rns_storage_dbg_mem(uint8_t *b, uint32_t _size) {
The leading `_` is probably a typo

2024-10-03 06:53 UTC, pennam requested changes
@maidnl you missed to change this line 

https://github.com/arduino/ArduinoCore-renesas/blob/0281be55e144227300bf9cc627d489f742a5f7bf/libraries/Storage/storage_common.h#L101

2024-10-03 07:22 UTC, pennam approved these changes
:+1:

2024-10-03 09:31 UTC, facchinm approved these changes

2024-10-03 10:56 UTC, merged